mediasancion/api0/core/urls.py
# coding: utf-8

# MediaSanción, aplicación web para acceder a los datos públicos de la
# actividad legislativa en Argentina.
# Copyright (C) 2010,2011,2012 Renzo Carbonara <renzo @carbonara .com .ar>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import

from django.conf.urls.defaults import *

from restsources import Handler
from restsources.restponders.json import JSONRestponder, JSONPRestponder
from restsources.restponders.xml import XMLRestponder

from .restsources import DistritoRestsource, PartidoRestsource, BloqueRestsource, PersonaRestsource


handler = Handler([JSONRestponder(), JSONPRestponder(), XMLRestponder()])



# URL namespace: api0:core:distritos
urlpatterns_distritos = patterns('',
    url(r'^$',
        handler,
        {'handler_options': {'restsource': DistritoRestsource(primary_fields_only=True),
                             'paginate_by': 200,
                             'paginate_by_max': 200 }},

        name='list'),

    url(r'^(?P<uuid>.+)/$',
        handler,
        {'handler_options': {'restsource': DistritoRestsource(), 'single': True}},
        name='detail'),
)


# URL namespace: api0:core:partidos
urlpatterns_partidos = patterns('',
    url(r'^$',
        handler,
        {'handler_options': {'restsource': PartidoRestsource(primary_fields_only=True),
                             'paginate_by': 50,
                             'paginate_by_max': 200 }},
        name='list'),

    url(r'^(?P<uuid>.+)/$',
        handler,
        {'handler_options': {'restsource': PartidoRestsource(), 'single': True}},
        name='detail'),
)


# URL namespace: api0:core:bloques
urlpatterns_bloques = patterns('',
    url(r'^$',
        handler,
        {'handler_options': {'restsource': BloqueRestsource(primary_fields_only=True),
                             'paginate_by': 50,
                             'paginate_by_max': 200 }},
        name='list'),

    url(r'^(?P<uuid>.+)/$',
        handler,
        {'handler_options': {'restsource': BloqueRestsource(), 'single': True}},
        name='detail'),
)

# URL namespace: api0:core:personas
urlpatterns_personas = patterns('',
    url(r'^$',
        handler,
        {'handler_options': {'restsource': PersonaRestsource(primary_fields_only=True),
                             'paginate_by': 50,
                             'paginate_by_max': 200 }},
        name='list'),

    url(r'^(?P<uuid>.+)/$',
        handler,
        {'handler_options': {'restsource': PersonaRestsource(), 'single': True}},
        name='detail'),
)

# URL namespace: api0:core
urlpatterns = patterns('',
    url(r'^distritos/', include(urlpatterns_distritos,
                                namespace='distritos', app_name='api0')),

    url(r'^partidos/', include(urlpatterns_partidos,
                                namespace='partidos', app_name='api0')),

    url(r'^bloques/', include(urlpatterns_bloques,
                                namespace='bloques', app_name='api0')),

    url(r'^personas/', include(urlpatterns_personas,
                                namespace='personas', app_name='api0')),
)

mediasancion/core/urls.py
# coding: utf-8
#
# MediaSanción, aplicación web para acceder a los datos públicos de la
# actividad legislativa en Argentina.
# Copyright (C) 2010,2011,2012 Renzo Carbonara <renzo @carbonara .com .ar>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import *


# core:bloques:
urlpatterns_bloques = patterns('mediasancion.core.views',
    url(r'^$',
        'bloque_list',
        name='list'),

    url(r'^(?P<slug>[-\w]+)/$',
        'bloque_detail',
        name='detail'),
)

# core:distritos:
urlpatterns_distritos = patterns('mediasancion.core.views',
    url(r'^$',
        'distrito_list',
        name='list'),

    url(r'^(?P<slug>[-\w]+)/$',
        'distrito_detail',
        name='detail'),
)

# core:personas:
urlpatterns_distritos = patterns('mediasancion.core.views',
    url(r'^(?P<slug>[-\w]+)/$',
        'persona_detail',
        name='detail'),
)

# core:
urlpatterns = patterns('',
    url(r'^bloques/',
        include(urlpatterns_bloques,
                namespace='bloques', app_name='core')),

    url(r'^distritos/',
        include(urlpatterns_distritos,
                namespace='distritos', app_name='core')),

    url(r'^personas/',
        include(urlpatterns_distritos,
                namespace='personas', app_name='core')),
)

mediasancion/urls.py
# coding: utf-8
#
# MediaSanción, aplicación web para acceder a los datos públicos de la
# actividad legislativa en Argentina.
# Copyright (C) 2010,2011,2012 Renzo Carbonara <renzo @carbonara .com .ar>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin

from haystack.views import search_view_factory

admin.autodiscover()


urlpatterns = patterns('',

# TEMPORARILY DISABLED. We are serving just the API right now.
#    url(r'^$', 'mediasancion.views.home', name='home'),
#    url(r'^search/$', 'mediasancion.search_views.search',
#        name='search'),

    url(r'^api/0/', include('mediasancion.api0.urls',
                            namespace='api0', app_name='api0'))


# TEMPORARILY DISABLED. We are serving just the API right now.
#    url(r'', include('mediasancion.core.urls',
#                     namespace='core', app_name='core')),
#
#    url(r'', include('mediasancion.congreso.urls',
#                     namespace='congreso', app_name='congreso')),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        # Static files
        url(r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
            'django.views.static.serve',
            { 'document_root': settings.MEDIA_ROOT, 'show_indexes': True } ),

        # Admin interface
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
        url(r'^admin/', include(admin.site.urls)),
    )

mediasancion/congreso/models.py
# coding: utf-8
#
# MediaSanción, aplicación web para acceder a los datos públicos de la
# actividad legislativa en Argentina.
# Copyright (C) 2010,2011,2012 Renzo Carbonara <renzo @carbonara .com .ar>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
from datetime import date, datetime
from django.utils.functional import curry

import Image

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

from django_extensions.db.fields import AutoSlugField, UUIDField

from mediasancion.utils.models import StandardAbstractModel


CAMARA_CHOICES = (
    ('S', _(u"Senadores")),
    ('D', _(u"Diputados")), )
CAMARA_DISPLAYS_SHORT = dict(CAMARA_CHOICES)
CAMARA_DISPLAYS_LONG = {
    'S': _(u"Cámara de Senadores"),
    'D': _(u"Cámara de Diputados") }
CAMARA_SLUGS = {
    'S': u'senadores',
    'D': u'diputados' }
CAMARA_LEGISLADOR_TIPO_DISPLAY = {
    'S': _(u'Senador'),
    'D': _(u'Diputado') }
# TODO : CAMARA_LEGISLADOR_TIPO_DISPLAY_FEMALE
CAMARA_LEGISLADOR_TIPO_DISPLAY_PLURAL = {
    'S': _(u'Senadores'),
    'D': _(u'Diputados') }


# This could be a metaclass, but I'm lazy right now.
def add_camara_text_utils_to_class(cls):
    """
    Adds camara values text representation utils to model fields whose
    `choices` is ``CAMARA_CHOICES``

    Added instance methods:

     - get_<fname>_slug(): slug text representation for camara value.
     - get_<fname>_display_long(): long text representation for camara value.
     - get_<fname>_display_short(): short text representation for camara value.
          This is the same value exposed by get_<fname>_display by default.
    """

    def _get_display(obj, attr, displays, default=u''):
        return displays.get(getattr(obj, attr), default)

    for f in cls._meta.fields:
        if f.choices is CAMARA_CHOICES:
            cls.add_to_class('get_%s_slug' % f.name,
                curry(_get_display, attr=f.name,
                                    displays=CAMARA_SLUGS))

            cls.add_to_class('get_%s_display_long' % f.name,
                curry(_get_display, attr=f.name,
                                    displays=CAMARA_DISPLAYS_LONG))

            # this is the same as self.get_<fname>_display. Added just for completeness
            cls.add_to_class('get_%s_display_short' % f.name,
                curry(_get_display, attr=f.name,
                                    displays=CAMARA_DISPLAYS_SHORT))


class Comision(StandardAbstractModel):
    uuid = UUIDField(version=4, unique=True, db_index=True)
    camara = models.CharField(max_length=1, choices=CAMARA_CHOICES)
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField(blank=True)
    slug = AutoSlugField(populate_from='nombre', overwrite=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name = _(u"comisión")
        verbose_name_plural = _(u"comisiones")
        unique_together = ('camara', 'nombre')

    @models.permalink
    def get_absolute_url(self):
        return 'congreso:%s:comisiones:detail' % self.get_camara_slug(), (self.slug,)

    @property
    @models.permalink
    def api0_url(self):
        return 'api0:congreso:comisiones:detail', (self.uuid,)

add_camara_text_utils_to_class(Comision)


class CurrentLegisladorManager(models.Manager):
    def get_query_set(self):
        now = datetime.now()
        return super(CurrentLegisladorManager, self) \
            .get_query_set().filter(inicio__lte=now, fin__gte=now)


class Legislador(StandardAbstractModel):
    uuid = UUIDField(version=4, unique=True, db_index=True)
    persona = models.ForeignKey('core.Persona', null=True)
    camara = models.CharField(max_length=1, choices=CAMARA_CHOICES) # '?' could mean we don't know.
    # XXX inicio, fin, partido and distrito shouldn't be null, but we have some missing data.
    inicio = models.DateField(null=True)
    fin = models.DateField(null=True)
    partido = models.ForeignKey('core.Partido', null=True)
    bloque = models.ForeignKey('core.Bloque', null=True)
    distrito = models.ForeignKey('core.Distrito', null=True)

    objects = models.Manager()
    current = CurrentLegisladorManager()

    class Meta:
        ordering = '-fin', '-inicio'

    @property
    @models.permalink
    def api0_url(self):
        return 'api0:congreso:legisladores:detail', (self.uuid,)

    def __unicode__(self):
        out = u'%s: %s' % (self.persona.full_name, self.get_camara_display_short())
        if self.inicio and self.fin:
            out += u' %s-%s' % (self.inicio.strftime('%Y'), self.fin.strftime('%Y'))
        return out

    @property
    def tipo_display(self):
        if self.camara == 'S':
            return _(u"Senador")
        elif self.camara == 'D':
            return _(u"Diputado")
        else:
            return _(u"Legislador")


    def save(self, *args, **kwargs):
        if self.inicio and self.fin and not self.inicio <= self.fin:
            raise ValueError('%s > %s' % (self.inicio, self.fin))
        return super(Legislador, self).save(*args, **kwargs)

add_camara_text_utils_to_class(Legislador)


class MembresiaComision(StandardAbstractModel):
    CARGO_CHOICES = (
        ('P', _(u'presidente')),
        ('Q', _(u'vicepresidente 1ro')),
        ('R', _(u'vicepresidente 2do')),
        ('S', _(u'secretario')),
        ('V', _(u'vocal')), )

    uuid = UUIDField(version=4, unique=True, db_index=True)
    legislador = models.ForeignKey(Legislador, null=True)
    comision = models.ForeignKey(Comision)
    cargo = models.CharField(max_length=1, choices=CARGO_CHOICES)



class Reunion(StandardAbstractModel):
    uuid = UUIDField(version=4, unique=True, db_index=True)
    camara = models.CharField(max_length=1, choices=CAMARA_CHOICES)
    nro_periodo = models.IntegerField()
    nro_reunion = models.IntegerField()
    titulo = models.CharField(max_length=128)
    fecha = models.DateField()

add_camara_text_utils_to_class(Reunion)


class AsistenciaReunion(StandardAbstractModel):
    ASISTENCIA_CHOICES = (
        ('P', _(u'presente')),
        ('A', _(u'ausente con aviso')),
        ('L', _(u'licencia')),
        ('M', _(u'mision oficial')), )

    uuid = UUIDField(version=4, unique=True, db_index=True)
    reunion = models.ForeignKey(Reunion)
    legislador = models.ForeignKey(Legislador, null=True)
    asistencia = models.CharField(max_length=1, choices=ASISTENCIA_CHOICES)


class Proyecto(StandardAbstractModel):
    TIPO_CHOICES = (
        ('L', _(u'ley')),
        ('D', _(u'declaración')),
        ('R', _(u'resolución')),
        ('C', _(u'comunicación')),
        ('E', _(u'decreto')),
        ('M', _(u'mensaje')), )

    ORIGEN_CHOICE = (
        ('S', _(u"cámara de senadores")),
        ('D', _(u"cámara de diputados")),
        ('E', _(u"poder ejecutivo")),
        ('J', _(u"jefe de gabinete")),
        ('O', _(u"organismos oficiales")),
        ('P', _(u"particular")), )

    uuid = UUIDField(version=4, unique=True, db_index=True)
    origen = models.CharField(max_length=1, choices=ORIGEN_CHOICE)
    camara_origen = models.CharField(max_length=1, choices=CAMARA_CHOICES)
    camara_origen_expediente = models.CharField(max_length=15)
    camara_revisora = models.CharField(max_length=1, choices=CAMARA_CHOICES, null=True, blank=True)
    camara_revisora_expediente = models.CharField(max_length=15)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    tipo_verbose = models.CharField(max_length=255)
    mensaje = models.CharField(max_length=15)
    sumario = models.TextField(blank=True)
    fundamentos = models.TextField(blank=True)
    firmantes_set = models.ManyToManyField(Legislador, through='FirmaProyecto')
    comisiones = models.ManyToManyField(Comision)
    texto_completo_url = models.URLField()
    texto_mediasancion_senadores_url = models.URLField()
    texto_mediasancion_diputados_url = models.URLField()
    publicacion_en = models.CharField(max_length=255)
    publicacion_fecha = models.DateField()
    reproduccion_expediente = models.CharField(max_length=16, blank=True)
    ley_numero = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        unique_together = ('camara_origen', 'camara_origen_expediente'),

    def __unicode__(self):
        if self.camara_revisora:
            camara_revisora_text = u" → %s" % self.camara_revisora_expediente
        else:
            camara_revisora_text = u""
        return (u"Proyecto de %(tipo)s %(camara_origen_expediente)s"
                u"%(camara_revisora_text)s") % {
                        'tipo': self.get_tipo_display().capitalize(),
                        'camara_origen_expediente': self.camara_origen_expediente,
                        'camara_revisora_text': camara_revisora_text }

    def get_absolute_url(self):
        return self.get_origen_pov_absolute_url()

    @models.permalink
    def get_origen_pov_absolute_url(self):
        return 'congreso:%s:proyectos:detail' % self.get_camara_origen_slug(), (self.camara_origen_expediente,)

    @models.permalink
    def get_revisora_pov_absolute_url(self):
        if self.camara_revisora:
            return 'congreso:%s:proyectos:detail' % self.get_camara_revisora_slug(), (self.camara_revisora_expediente,)

    @property
    @models.permalink
    def api0_url(self):

mediasancion/core/templates/core/bloque_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load utils_html %}

{% block bodyid %}bloque-detail{% endblock %}

{% block content %}
  <article id="{{ bloque.uuid }}" class="bloque content-wrap">
    <div class="legisladores">
      <p>
        {% trans "Legisladores actualmente en el Congreso" %}:
        <strong><span class="legislador-count">{{ bloque.denorm_legisladores.count }}</span></strong>
      </p>
      {% if bloque.legislador_set %}
        <ul>
          {% for legislador in bloque.denorm_legisladores %}
            <li class="legislador" id="{{ legislador.uuid }}">
              {{ legislador.persona|objlink }}
            </li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
  </article>
{% endblock %}

mediasancion/core/templates/core/bloque_list.html
{% extends "base.html" %}
{% load i18n %}
{% load utils_html %}

{% block bodyid %}bloque-list{% endblock %}

{% block content %}
  <section class="bloques content-wrap">
    {% for bloque in bloques %}
      <article class="bloque" id="{{ bloque.uuid }}">
        <h1><a href="{{ bloque.get_absolute_url }}">{{ bloque.nombre }}</a></h1>
        <div class="legisladores">
          <p>
            {% trans "Legisladores actualmente en el Congreso" %}:
            <strong><span class="legislador-count">{{ bloque.legislador__count }}</span></strong>
          </p>
        </div>
      </article>
    {% endfor %}
  </section>
{% endblock %}

mediasancion/core/templates/core/persona_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load utils_html %}
{% load congreso %}

{% block bodyid %}persona-detail{% endblock %}

{% block content %}
  <article class="persona" id="{{ persona.uuid }}">

    <dl class="data">
      {% if persona.documento_tipo and persona.documento_numero %}
        <dt class="documento">{% trans "Documento de Identidad" %}</dt>
        <dd class="documento">
          <span class="documento-tipo">{{ persona.documento_tipo }}</span>
          <span class="documento-numero">{{ persona.documento_numero }}</span>
        </dd>
      {% endif %}
      {% if persona.email %}
        <dt class="email">{% trans "Email" %}</dt>
        <dd class="email">{{ persona.email }}</dd>
      {% endif %}
      {% if persona.telefono %}
        <dt class="telefono">{% trans "Teléfono" %}</dt>
        <dd class="telefono">{{ persona.telefono }}</dd>
      {% endif %}
      {% if persona.website %}
        <dt class="website">{% trans "Sitio Web" %}</dt>
        <dd class="website">{{ persona.website }}</dd>
      {% endif %}
    </dl>

    {% if legislador_current %}
      <section class="legislador-current legislador">
        <h1>
          {% blocktrans with legislador_tipo=legislador_current.camara|camara_legislador_tipo_display distrito=legislador_current.distrito|objlink %}
            Actual {{ legislador_tipo }} de {{ distrito }}
          {% endblocktrans %}
        </h1>
        <div class="details">
          <p>
            {% trans "Por el bloque" %} <span class="bloque" data-bloque="{{ legislador_current.bloque.uuid }}">{{ legislador_current.bloque|objlink }}</span>,
            {% trans "desde" %} <span class="inicio" data-fecha-inicio="{{ legislador_current.inicio|date:"c" }}">{{ legislador_current.inicio|date:"F Y" }}</span>
            <strong>{% trans "hasta" %} <span class="fin" data-fecha-fin="{{ legislador_current.fin|date:"c" }}">{{ legislador_current.fin|date:"F Y" }}</span></strong>.
          </p>
          <!-- MOCK data <p>Asistencia: 25 de 30 reuniones durante su cargo.*</p> -->

        <!-- MOCK DATA
        <h2>{% trans "Comisiones a las que pertenece" %}*</h2>
        <ul>
          <li><a href="/diputados/comisiones/relaciones-exteriores-y-culto/">Relaciones exteriores y culto</a></li>
          <li><a href="/diputados/comisiones/legislacion-general/">Legislacion general</a></li>
          <li><a href="/diputados/comisiones/deportes/">Deportes</a></li>
          <li><a href="/diputados/comisiones/presupuesto-y-hacienda/">Presupuesto y hacienda</a></li>
        </ul> -->

        <!-- MOCK DATA
        <h2>{% trans "Proyectos presentados" %}*</h2>
        <ul>
          <li><p><a href="/diputados/proyectos/5195-D-2011/">5195-D-2011</a>: Solicitar al poder ejecutivo disponga las medidas necesarias para la creacion de la embajada argentina en la republica de azerbaiyan.</p></li>
          <li><p><a href="/diputados/proyectos/5194-D-2011/">5194-D-2011</a>: Tranferencia a titulo gratuito del predio propiedad del estado nacional ubicado en chilecito, provincia de la rioja, a favor del club atletico, cultural y deportivo san buenaventura de la mencionada provincia.</p></li>
          <li><p><a href="/diputados/proyectos/5193-D-2011/">5193-D-2011</a>: Solicitar al poder ejecutivo disponga la inclusion en el programa nacional &quot;mas escuelas ii&quot;, la construccion y equipamiento del edificio de la escuela 389 &quot;tinkunaco&quot;, en la provincia de la rioja.</p></li>
          <li><p><a href="/diputados/proyectos/5192-D-2011/">5192-D-2011</a>: Expresar beneplacito por la inauguracion de la construccion del &quot;polo cientifico y tecnologico&quot;, en terrenos de las ex - bodegas giol, en la ciudad autonoma de buenos aires.</p></li>
        </ul> -->

        <h2>{% trans "Proyectos firmados" %}</h2>
        <ul>
          {% for p in legislador_current.firmaproyecto_set.all %}
            <li><p>{{ p.proyecto|objlink }}: {{ p.proyecto.sumario|lower|capfirst }}</p></li>
          {% endfor %}
        </ul>

      </section>
    {% endif %}

  </article>

    {% if legislador_past_list.count %}
      <section class="legislador-past">
        <h2>{% trans "Cargos anteriores" %}</h1>
        <ul>
          {% for legislador in legislador_past_list %}
            <li class="legislador" id="{{ legislador.uuid }}">
              <p>
                {% if legislador.inicio or legislador.fin %}
                  <span class="fecha">
                    {% filter capfirst %}
                      {% if legislador.inicio %}
                        desde <span class="inicio" data-fecha-inicio="{{ legislador.inicio|date:"c" }}">{{ legislador.inicio|date:"F Y" }}</span>
                      {% endif %}
                      {% if legislador.fin %}
                        hasta <span class="fin" data-fecha-fin="{{ legislador.fin|date:"c" }}">{{ legislador.fin|date:"F Y" }}</span>
                      {% endif %}
                    {% endfilter %}
                  </span>
                  —
                {% endif %}
                <span class="cargo" data-camara="{{ legislador.camara }}">{{ legislador.camara|camara_legislador_tipo_display }}</span>
                {% trans "de" %}
                <span class="distrito" data-distrito="{{ legislador.distrito.uuid }}">{{ legislador.distrito|objlink }}</span>,
                {% trans "por el bloque" %}
                <span class="bloque" data-bloque="{{ legislador.bloque.uuid }}">{{ legislador.bloque|objlink }}</span>.
              </p>
            </li>
          {% endfor %}
        </ul>
      </section>
    {% endif %}

  </article>
{% endblock %}